name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls
      - name: cd Platform.Data.Triplets.Kernel/ && ls
        run: cd Platform.Data.Triplets.Kernel/ && ls
      - name: ls
        run: ls
      - name: make
        run: make
      - name: ./test
        run: ./test
      - name: cd ..
        run: cd ..
