name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls
      - name: Cd in folder, show ls and make
        run: |
          cd Platform.Data.Triplets.Kernel/
          ls
          make
          ./test |
        
      - name: cd
        run: cd
